FROM node:16
WORKDIR /app
COPY package.json .

ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \
        then npm install; \
        else npm install --only=production; \
        fi

COPY . ./
ENV FRONTEND_PORT 3001
EXPOSE $FRONTEND_PORT
CMD ["npm", "start"]
