version: "3"
services:
  oilstone-backend:
    build: "./backend"
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    environment:
      - HOST=${HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  oilstone-frontend:
    build: "./frontend"
    volumes:
      - ./frontend:/app/
      - ./frontend/node_modules
    ports:
      - "3001:3001"
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - '../postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
