version: "3"
services:
  oilstone:
    build: 
      context: .
      args: 
        NODE_ENV: production
    command: node index.js
    depends_on:
      - "db"
  db:
    ports:
      - "5432:5432"
    restart: always
