version: "3"
services:
  oilstone:
    build: 
      context: .
      args: 
        NODE_ENV: development
      depends_on:
      - "db"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
  db:
